name: clique_king
description: "A social platform with score based leaderboards."
publish_to: 'none'
repository: https://github.com/BaraShiro/CliqueKingApp

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  meta: ^1.10.0
  fpdart: ^1.1.0
  uuid: ^4.0.0
  string_validator: ^1.0.2
  path_provider: ^2.1.1
  material_symbols_icons: ^4.2709.0
  side_effect_bloc: ^1.0.0
  collection: ^1.18.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true